
name: git-action-test-woekflow-1
on: push

jobs:
  job-id-01:
    name: job-01
    runs-on: ubuntu-latest
    needs: ['job-id-03']
    steps:
    
    - name: Print env
      env:
        MY_VAR: Hi! My name is
        FIRST_NAME: ZHANG SAN
      run: echo $MY_VAR $FIRST_NAME.
      
    - name: Install go and print go version
      uses: actions/setup-go@v3
      with: 
        go-version: '1.18.0-rc.1'
    - run: go version
    
    - name: Install JDK and print java&maven version
      uses: actions/setup-java@v3
      with: 
        distribution: 'temurin'
        java-version: '11'
    - run: java -version & mvn -v
      
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Run java app
      run: |
        pwd
        cd cloud-service
        mvn clean package
        ls -l
        
    - name: Upload java artifact
      uses: actions/upload-artifact@main
      with:
        name: clocloud-service-app
        path: ./cloud-service/target/cloud-service-1.0.0-SNAPSHOT.jar
    - run: pwd
    
    - name: Build go app
      run: |
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o println.exe println.go
        ls -l
      
    - name: Upload go artifact
      uses: actions/upload-artifact@main
      with:
        name: println-app
        path: ./println.exe
  
  
  job-id-02:
    name: job-02
    runs-on: windows-latest
    needs: ['job-id-03']
    steps:
    - name: Print network info
      run: ipconfig
      
  job-id-03:
    name: job-03
    runs-on: ubuntu-latest
    steps:
    - name: Print date
      run: date
      
  job-id-04:
    name: job-04
    runs-on: windows-latest
    needs: ['job-id-03','job-id-02']
    steps:
    - name: Print disk info
      run: df -hl
      
  job-id-05:
    name: job-05
    runs-on: windows-latest
    steps:
    
    - name: Install JDK and print java&maven version
      uses: actions/setup-java@v3
      with: 
        distribution: 'temurin'
        java-version: '11'
    - run: java -version
    
    - name: Compile check
      run: javac Demo.java
