
name: git-action-test-ci-demo1
on: push

jobs:
  job-id-01:
    name: job-02
    runs-on: ubuntu-latest
    needs: ['job-id-03']
    steps:
    
    - name: Print env
      env:
        MY_VAR: Hi! My name is
        FIRST_NAME: ZHANG SAN
      run: echo $MY_VAR $FIRST_NAME.
      
    - name: install go and print go version
      uses: actions/setup-go@v3
      with: 
        go-version: '1.18.0-rc.1'
    - run: go version
    
    - name: Install JDK and print java&maven version
      uses: actions/setup-java@v3
      with: 
        distribution: 'temurin'
        java-version: '11'
    - run: java -version & mvn -v
      
    - name: checkout
      uses: actions/checkout@v3
      
    - name: run java app
      run: pwd & java Demo.java
    
    - name: build go app
      run: |
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o println.exe println.go
        ls -l
      
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: ./println.exe
  
  
  job-id-02:
    name: job-01
    runs-on: windows-latest
    needs: ['job-id-03']
    steps:
    - name: Print network info
      run: ipconfig
      
  job-id-03:
    name: job-03
    runs-on: ubuntu-latest
    steps:
    - name: Print date
      run: date
        
